 <?php
    $payload = array(
        array(
            "email" => 'laura@loveandhoneyfriedchicken.com',
            "password" => 'greenstreet@2025?',
            "firstName" => '',
            "lastName" => '',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Philadelphia',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'Love & Honey Fried Chicken',
            "businessType" => 'Buyer',
            "billingZipCode" => '19123',
            "taxIdNumber" => '',
            "billingAddressLine1" => '1100 N. Front Street',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'mabukitchen@outlook.com',
            "password" => 'greenstreet@2025?',
            "firstName" => 'Ayad',
            "lastName" => 'Sinawi',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Philadelphia',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'Mabu',
            "businessType" => 'Buyer',
            "billingZipCode" => '19107',
            "taxIdNumber" => '',
            "billingAddressLine1" => '1120 Pine Street',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'arenasmaria67@gmail.com',
            "password" => 'greenstreet@2025?',
            "firstName" => 'Maria',
            "lastName" => 'Arenas',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Philadelphia',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'Maria Arenas',
            "businessType" => 'Buyer',
            "billingZipCode" => '19148',
            "taxIdNumber" => '',
            "billingAddressLine1" => '2101 S. 3rd St.',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'primaryplantbased@gmail.com',
            "password" => 'greenstreet@2025?',
            "firstName" => 'Mark',
            "lastName" => 'McKinney',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Philadelphia',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'Mark McKinney',
            "businessType" => 'Buyer',
            "billingZipCode" => '19125',
            "taxIdNumber" => '',
            "billingAddressLine1" => '161 W. Girard Ave',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'store@nextstopcoffee.com',
            "password" => 'greenstreet@2025?',
            "firstName" => 'Kristina',
            "lastName" => 'Minister',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Ardmore',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'Next Stop Coffee',
            "businessType" => 'Buyer',
            "billingZipCode" => '19003',
            "taxIdNumber" => '',
            "billingAddressLine1" => '2528 Haverford Road',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'nomnamhouse@gmail.com',
            "password" => 'greenstreet@2025?',
            "firstName" => 'Wiley',
            "lastName" => 'Kollar',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Media',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'Nom Nam House',
            "businessType" => 'Buyer',
            "billingZipCode" => '19063',
            "taxIdNumber" => '',
            "billingAddressLine1" => '433 Manchester Ave',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'pandemicpantryphilly@gmail.com',
            "password" => 'greenstreet@2025?',
            "firstName" => 'Ann',
            "lastName" => 'Karlen',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Philadelphia',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '(215) 206-2227',
            "businessName" => 'Pandemic Pantry',
            "businessType" => 'Buyer',
            "billingZipCode" => '19143',
            "taxIdNumber" => '',
            "billingAddressLine1" => '705 S. 50th Street',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'AJ.Buchanan@wholefoods.com',
            "password" => 'greenstreet@2025?',
            "firstName" => 'Whole',
            "lastName" => 'Foods #88',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Philadelphia',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'PHILLY CENTER CITY WHOLEFOODS #88',
            "businessType" => 'Buyer',
            "billingZipCode" => '19130',
            "taxIdNumber" => '',
            "billingAddressLine1" => '2101 Pennsylvania Ave',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),


        array(
            "email" => 'Tanya.Cain@wholefoods.com',
            "password" => 'greenstreet@2025?',
            "firstName" => 'Whole',
            "lastName" => 'Foods',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Plymouth Meeting',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '6108320010',
            "businessName" => 'Plymouth Meeting Whole Foods',
            "businessType" => 'Buyer',
            "billingZipCode" => '19462',
            "taxIdNumber" => '',
            "billingAddressLine1" => '500 W Germantown Pike',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),

        array(
            "email" => 'Craig.Harris@wholefoods.com',
            "password" => 'greenstreet@2025?',
            "firstName" => '',
            "lastName" => '',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Princeton',
            "billingState" => 'NJ',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'Princeton Whole Foods #55',
            "businessType" => 'Buyer',
            "billingZipCode" => '1112',
            "taxIdNumber" => '',
            "billingAddressLine1" => '',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'quetrinh67@gmail.com',
            "password" => 'greenstreet@2025?',
            "firstName" => 'Que',
            "lastName" => 'Trinh',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Philadelphia',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'Que Trinh',
            "businessType" => 'Buyer',
            "billingZipCode" => '19143',
            "taxIdNumber" => '',
            "billingAddressLine1" => '4653 Walnut Street Greenstreet Coffee Company',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'katie.steenstra@gmail.com',
            "password" => 'greenstreet@2025?',
            "firstName" => '',
            "lastName" => '',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Philadelphia',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'Renata\'s Kitchen',
            "businessType" => 'Buyer',
            "billingZipCode" => '19143',
            "taxIdNumber" => '',
            "billingAddressLine1" => '3940 Baltimore Ave',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'nick@sojournphilly.com',
            "password" => 'greenstreet@2025?',
            "firstName" => '',
            "lastName" => '',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Philadelphia',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'Rex at The Royal',
            "businessType" => 'Buyer',
            "billingZipCode" => '19146',
            "taxIdNumber" => '',
            "billingAddressLine1" => '1524 South Street',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),

        array(
            "email" => 'travis@rowhousegrocery.com',
            "password" => 'greenstreet@2025?',
            "firstName" => 'Travis',
            "lastName" => 'Weissman',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Philadelphia',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'Row House Grocery',
            "businessType" => 'Buyer',
            "billingZipCode" => '19145',
            "taxIdNumber" => '',
            "billingAddressLine1" => '1713 Mckean st',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'woodshelfcafe@gmail.com',
            "password" => 'greenstreet@2025?',
            "firstName" => 'Sabre',
            "lastName" => 'Williams',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Benton',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'Sabre Williams',
            "businessType" => 'Buyer',
            "billingZipCode" => '17814',
            "taxIdNumber" => '',
            "billingAddressLine1" => 'PO BOX 118',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'info@bar1010.com',
            "password" => 'greenstreet@2025?',
            "firstName" => '',
            "lastName" => '',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Philadelphia',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'Slice and Schmear',
            "businessType" => 'Buyer',
            "billingZipCode" => '19148',
            "taxIdNumber" => '',
            "billingAddressLine1" => '1700 S 10th St',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'culinary@porcosphilly.com',
            "password" => 'greenstreet@2025?',
            "firstName" => '',
            "lastName" => '',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'New Bold',
            "billingState" => 'Philadelphia',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'Small Oven Pastries',
            "businessType" => 'Buyer',
            "billingZipCode" => '1112',
            "taxIdNumber" => '',
            "billingAddressLine1" => '',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'nick@sojournphilly.com',
            "password" => 'greenstreet@2025?',
            "firstName" => 'Sor',
            "lastName" => 'Ynez',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Philadelphia',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'Sor Ynez',
            "businessType" => 'Buyer',
            "billingZipCode" => '19123',
            "taxIdNumber" => '',
            "billingAddressLine1" => '1800 N American Street',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'bookkeeper@southphillyfood.coop',
            "password" => 'greenstreet@2025?',
            "firstName" => 'Christo',
            "lastName" => 'Johnson',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Philadelphia',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '(215) 920-1100',
            "businessName" => 'South Philly Food Co-Op',
            "businessType" => 'Buyer',
            "billingZipCode" => '19148',
            "taxIdNumber" => '',
            "billingAddressLine1" => '2031 S Juniper St',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'rhianna.spiro@wholefoods.com',
            "password" => 'greenstreet@2025?',
            "firstName" => 'Whole',
            "lastName" => 'Foods #41',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Philadelphia',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'South Street Whole Foods #41',
            "businessType" => 'Buyer',
            "billingZipCode" => '19147',
            "taxIdNumber" => '',
            "billingAddressLine1" => 'South Street Whole Foods, Mid Atlantic Store #41',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'Timothy.Martz@wholefoods.com',
            "password" => 'greenstreet@2025?',
            "firstName" => 'Spring',
            "lastName" => 'House Whole Foods',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Spring House',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '(215) 646-6300',
            "businessName" => 'Spring House Whole Foods',
            "businessType" => 'Buyer',
            "billingZipCode" => '19477',
            "taxIdNumber" => '',
            "billingAddressLine1" => '1111 North Bethlehem Pike',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        ),
        array(
            "email" => 'info@thetricycleshop.com',
            "password" => 'greenstreet@2025?',
            "firstName" => 'Spring',
            "lastName" => 'Mill',
            "receiveEmailNotifications" => true,
            "billingCountry" => 'USA',
            "billingCity" => 'Conshohocken',
            "billingState" => 'PA',
            "preferredLanguage" => 'english',
            "phoneNumber" => '',
            "businessName" => 'Spring Mill',
            "businessType" => 'Buyer',
            "billingZipCode" => '19148',
            "taxIdNumber" => '',
            "billingAddressLine1" => '555 E. North Lane',
            "billingAddressLine2" => '',
            "userRole" => 'Buyer',
            "userType" => 'Buyer'
        )


    );


    $payload = array(
        array(
            "email" => "nhatminhletu195@gmail.com",
            "password" => "greenstreet@2025?",
            "firstName" => "Minh",
            "lastName" => "Le Tu",
            "receiveEmailNotifications" => true,
            "billingCountry" => "USA",
            "billingCity" => "Philadelphia",
            "billingState" => "PA",
            "preferredLanguage" => "english",
            "phoneNumber" => "",
            "businessName" => "Sun Cafe",
            "businessType" => "Buyer",
            "billingZipCode" => "19143",
            "taxIdNumber" => "",
            "billingAddressLine1" => "4653 Walnut Street",
            "billingAddressLine2" => "",
            "userRole" => "Buyer",
            "userType" => "Buyer"
        ),
        array(
            "email" => "trichardett@ardentheatre.org",
            "password" => "greenstreet@2025?",
            "firstName" => "Tanner",
            "lastName" => "Richardett",
            "receiveEmailNotifications" => true,
            "billingCountry" => "USA",
            "billingCity" => "Philadelphia",
            "billingState" => "PA",
            "preferredLanguage" => "english",
            "phoneNumber" => "",
            "businessName" => "Tanner Richardett",
            "businessType" => "Buyer",
            "billingZipCode" => "19103",
            "taxIdNumber" => "",
            "billingAddressLine1" => "40 N. 2nd Street",
            "billingAddressLine2" => "",
            "userRole" => "Buyer",
            "userType" => "Buyer"
        ),
        array(
            "email" => "mclouse@tenth.org",
            "password" => "greenstreet@2025?",
            "firstName" => "Matt",
            "lastName" => "Clouse",
            "receiveEmailNotifications" => true,
            "billingCountry" => "USA",
            "billingCity" => "Philadelphia",
            "billingState" => "PA",
            "preferredLanguage" => "english",
            "phoneNumber" => "",
            "businessName" => "Tenth Preysbyterian Church",
            "businessType" => "Buyer",
            "billingZipCode" => "19103",
            "taxIdNumber" => "",
            "billingAddressLine1" => "1701 Delancey Street",
            "billingAddressLine2" => "",
            "userRole" => "Buyer",
            "userType" => "Buyer"
        ),
        array(
            "email" => "tracyn9@msn.com",
            "password" => "greenstreet@2025?",
            "firstName" => "",
            "lastName" => "",
            "receiveEmailNotifications" => true,
            "billingCountry" => "USA",
            "billingCity" => "Wales",
            "billingState" => "PA",
            "preferredLanguage" => "english",
            "phoneNumber" => "",
            "businessName" => "The Green Fork",
            "businessType" => "Buyer",
            "billingZipCode" => "19454",
            "taxIdNumber" => "",
            "billingAddressLine1" => "115 S. Main St. N.",
            "billingAddressLine2" => "",
            "userRole" => "Buyer",
            "userType" => "Buyer"
        ),
        array(
            "email" => "badetske78@gmail.com",
            "password" => "greenstreet@2025?",
            "firstName" => "",
            "lastName" => "",
            "receiveEmailNotifications" => true,
            "billingCountry" => "USA",
            "billingCity" => "Philadelphia",
            "billingState" => "PA",
            "preferredLanguage" => "english",
            "phoneNumber" => "",
            "businessName" => "The Green Rock Tavern",
            "businessType" => "Buyer",
            "billingZipCode" => "19125",
            "taxIdNumber" => "",
            "billingAddressLine1" => "2546 E Lehigh Ave",
            "billingAddressLine2" => "",
            "userRole" => "Buyer",
            "userType" => "Buyer"
        ),
        array(
            "email" => "nouvauxmarket@gmail.com",
            "password" => "greenstreet@2025?",
            "firstName" => "Rodney",
            "lastName" => "Pagan",
            "receiveEmailNotifications" => true,
            "billingCountry" => "USA",
            "billingCity" => "Philadelphia",
            "billingState" => "PA",
            "preferredLanguage" => "english",
            "phoneNumber" => "",
            "businessName" => "The NouVaux Market",
            "businessType" => "Buyer",
            "billingZipCode" => "19129",
            "taxIdNumber" => "",
            "billingAddressLine1" => "3539 Vaux St",
            "billingAddressLine2" => "",
            "userRole" => "Buyer",
            "userType" => "Buyer"
        ),
        array(
            "email" => "info@thetricycleshop.com",
            "password" => "greenstreet@2025?",
            "firstName" => "",
            "lastName" => "",
            "receiveEmailNotifications" => true,
            "billingCountry" => "USA",
            "billingCity" => "New Bold",
            "billingState" => "Philadelphia",
            "preferredLanguage" => "english",
            "phoneNumber" => "",
            "businessName" => "Tricycle Cafe",
            "businessType" => "Buyer",
            "billingZipCode" => "1112",
            "taxIdNumber" => "",
            "billingAddressLine1" => "",
            "billingAddressLine2" => "",
            "userRole" => "Buyer",
            "userType" => "Buyer"
        ),
        array(
            "email" => "triplecangus5@gmail.com",
            "password" => "greenstreet@2025?",
            "firstName" => "",
            "lastName" => "",
            "receiveEmailNotifications" => true,
            "billingCountry" => "USA",
            "billingCity" => "Pilesgrove",
            "billingState" => "NJ",
            "preferredLanguage" => "english",
            "phoneNumber" => "",
            "businessName" => "Triple C Angus",
            "businessType" => "Buyer",
            "billingZipCode" => "08098",
            "taxIdNumber" => "",
            "billingAddressLine1" => "110 Old Salem Road",
            "billingAddressLine2" => "",
            "userRole" => "Buyer",
            "userType" => "Buyer"
        ),
        array(
            "email" => "eacook04@yahoo.com",
            "password" => "greenstreet@2025?",
            "firstName" => "Emily",
            "lastName" => "Cook",
            "receiveEmailNotifications" => true,
            "billingCountry" => "USA",
            "billingCity" => "Ligonier",
            "billingState" => "PA",
            "preferredLanguage" => "english",
            "phoneNumber" => "",
            "businessName" => "Tubmill Creek Provisions",
            "businessType" => "Buyer",
            "billingZipCode" => "15658",
            "taxIdNumber" => "",
            "billingAddressLine1" => "106 N St Clair",
            "billingAddressLine2" => "Coffee Shop",
            "userRole" => "Buyer",
            "userType" => "Buyer"
        ),
        array(
            "email" => "diana@vaultandvine.co",
            "password" => "greenstreet@2025?",
            "firstName" => "",
            "lastName" => "",
            "receiveEmailNotifications" => true,
            "billingCountry" => "USA",
            "billingCity" => "Philadelphia",
            "billingState" => "PA",
            "preferredLanguage" => "english",
            "phoneNumber" => "",
            "businessName" => "Vault + Vine",
            "businessType" => "Buyer",
            "billingZipCode" => "19129",
            "taxIdNumber" => "",
            "billingAddressLine1" => "3507 Midvale Ave",
            "billingAddressLine2" => "",
            "userRole" => "Buyer",
            "userType" => "Buyer"
        ),
        array(
            "email" => "nfordham@weaversway.coop",
            "password" => "greenstreet@2025?",
            "firstName" => "Weavers",
            "lastName" => "Way",
            "receiveEmailNotifications" => true,
            "billingCountry" => "USA",
            "billingCity" => "Philadelphia",
            "billingState" => "PA",
            "preferredLanguage" => "english",
            "phoneNumber" => "",
            "businessName" => "Weavers Way Carpenter Lane",
            "businessType" => "Buyer",
            "billingZipCode" => "19119",
            "taxIdNumber" => "",
            "billingAddressLine1" => "559 Carpenter Lane",
            "billingAddressLine2" => "",
            "userRole" => "Buyer",
            "userType" => "Buyer"
        ),
        array(
            "email" => "kwalker@weaversway.coop",
            "password" => "greenstreet@2025?",
            "firstName" => "Weavers",
            "lastName" => "Way",
            "receiveEmailNotifications" => true,
            "billingCountry" => "USA",
            "billingCity" => "Philadelphia",
            "billingState" => "PA",
            "preferredLanguage" => "english",
            "phoneNumber" => "",
            "businessName" => "Weavers Way Cooperative",
            "businessType" => "Buyer",
            "billingZipCode" => "19118",
            "taxIdNumber" => "",
            "billingAddressLine1" => "8424 Germantown Avenue",
            "billingAddressLine2" => "",
            "userRole" => "Buyer",
            "userType" => "Buyer"
        ),

        array(
            "email" => "doyrecieving@wholefoods.com",
            "password" => "greenstreet@2025?",
            "firstName" => "",
            "lastName" => "",
            "receiveEmailNotifications" => true,
            "billingCountry" => "USA",
            "billingCity" => "Doylestown",
            "billingState" => "PA",
            "preferredLanguage" => "english",
            "phoneNumber" => "(267) 915-6880",
            "businessName" => "Whole Foods Doylestown",
            "businessType" => "Buyer",
            "billingZipCode" => "",
            "taxIdNumber" => "",
            "billingAddressLine1" => "1745 S Easton Road Suite E1",
            "billingAddressLine2" => "",
            "userRole" => "Buyer",
            "userType" => "Buyer"
        ),


        array(
            "email" => "lvskaare@gmail.com",
            "password" => "greenstreet@2025?",
            "firstName" => "Louise",
            "lastName" => "Skaare",
            "receiveEmailNotifications" => true,
            "billingCountry" => "USA",
            "billingCity" => "Williston",
            "billingState" => "ND",
            "preferredLanguage" => "english",
            "phoneNumber" => "",
            "businessName" => "Young Bucks, LLC",
            "businessType" => "Buyer",
            "billingZipCode" => "58801",
            "taxIdNumber" => "",
            "billingAddressLine1" => "1905 26th Street W",
            "billingAddressLine2" => "",
            "userRole" => "Buyer",
            "userType" => "Buyer"
        ),
        array(
            "email" => "zlati.stoyanov@gmail.com",
            "password" => "greenstreet@2025?",
            "firstName" => "Zlati",
            "lastName" => "Stoyanov",
            "receiveEmailNotifications" => true,
            "billingCountry" => "USA",
            "billingCity" => "Harleysville",
            "billingState" => "PA",
            "preferredLanguage" => "english",
            "phoneNumber" => "(267) 679-4692",
            "businessName" => "Zlati Stoyanov",
            "businessType" => "Buyer",
            "billingZipCode" => "19446",
            "taxIdNumber" => "",
            "billingAddressLine1" => "422 Main Street Apt. 91",
            "billingAddressLine2" => "",
            "userRole" => "Buyer",
            "userType" => "Buyer"
        )
    );
